# Generated by Django 4.2.7 on 2026-05-03 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(help_text='Maximum 100 characters', max_length=100, verbose_name='Ad')),
                ('last_name', models.CharField(help_text='Maximum 100 characters', max_length=100, verbose_name='Soyad')),
                ('email_address', models.EmailField(max_length=254, verbose_name='İstifadeçi E-mail')),
                ('address', models.CharField(help_text='Maximum 255 characters', max_length=255, verbose_name='Ünvanınız')),
                ('city', models.CharField(help_text='Maximum 255 characters', max_length=255, verbose_name='Şəhər')),
                ('tel_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon nömrəsi')),
                ('order_note', models.TextField(blank=True, null=True, verbose_name='Sifariş qeydi')),
                ('shipping_first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ad')),
                ('shipping_last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Soyad')),
                ('shipping_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('shipping_city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Şəhər')),
                ('shipping_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ünvan')),
                ('shipping_phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sifariş',
                'verbose_name_plural': 'Sifarişlər',
            },
        ),
        migrations.CreateModel(
            name='WishlistModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='Products.productmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'İstək Listəsi',
                'verbose_name_plural': 'İstək Listəsi',
                'ordering': ['created'],
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='Products.productmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Səbət Əşyası',
                'verbose_name_plural': 'Səbət Əşyaları',
                'ordering': ['created'],
                'unique_together': {('user', 'product')},
            },
        ),
    ]
