version: '3.8'
# Run All Services
services:
  # Run Service
  postgres:
    container_name: postgres
    image: postgres
    restart: "always"
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/
    env_file: .env

