version: '3.1'

services:
  postgres:
    container_name: postgres
    image: postgres:13   # versiyanı aşağı saldım
    restart: "always"
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    env_file: .env