# Generated by Django 5.1.3 on 2026-05-10 18:16

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'İstifadeçi',
                'verbose_name_plural': 'Admin',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('gender', models.PositiveSmallIntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')], default=1)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon nömrəsi')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='Profil şəkili')),
                ('receive_offers', models.BooleanField(default=False, verbose_name='Təkifləri nəzərdən keçirin')),
                ('subscribe_newsletter', models.BooleanField(default=False, verbose_name='Xəbər büllentinə abonə olun')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'İstifadəçi',
                'verbose_name_plural': 'İstifadəçi Profilləri',
            },
        ),
        migrations.CreateModel(
            name='ContactUsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(help_text='Maksimum 255 simvol', max_length=255, verbose_name='Ad')),
                ('last_name', models.CharField(help_text='Maksimum 255 simvol', max_length=255, verbose_name='Soyad')),
                ('email_address', models.EmailField(help_text='Düzgün email formatı daxil edin', max_length=254, verbose_name='Email Ünvanı')),
                ('subject', models.CharField(help_text='Maksimum 255 simvol', max_length=255, verbose_name='Mövzu')),
                ('message', models.TextField(help_text='Mesajınızı daxil edin', verbose_name='Mesaj')),
                ('is_read', models.BooleanField(default=False, help_text='Admin tərəfindən oxundu?', verbose_name='Oxundu')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='İstifadəçi')),
            ],
            options={
                'verbose_name': 'Əlaqə Mesajı',
                'verbose_name_plural': 'Əlaqə Mesajları',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ContactLocationsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(blank=True, help_text='Maksimum 255 simvol', max_length=255, null=True, verbose_name='Ünvan')),
                ('call_us', models.CharField(blank=True, help_text='Maksimum 20 simvol', max_length=20, null=True, verbose_name='Telefon')),
                ('email_us', models.EmailField(blank=True, help_text='Email ünvanı', max_length=254, null=True, verbose_name='Email')),
                ('location', models.CharField(blank=True, help_text='Maksimum 255 simvol (Google Maps linki və ya ünvan)', max_length=255, null=True, verbose_name='Lokasiya')),
                ('is_active', models.BooleanField(default=True, help_text='Bu məlumat aktivdir? (Yalnız bir aktiv məlumat ola bilər)', verbose_name='Aktiv')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='İstifadəçi')),
            ],
            options={
                'verbose_name': 'Məkan Məlumatları',
                'verbose_name_plural': 'Əlaqə Məlumatları',
                'ordering': ['-is_active', '-created'],
            },
        ),
    ]
