# Generated by Django 4.2.7 on 2026-05-03 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Maximum 50 character', max_length=50, verbose_name='Kateqoriya növü')),
                ('descriptions', models.TextField(blank=True, null=True, verbose_name='Kateqoriya haqqında')),
            ],
            options={
                'verbose_name': 'Kateqoriya',
                'verbose_name_plural': 'Kateqoriyalar',
            },
        ),
        migrations.CreateModel(
            name='ColorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Maximum 50 character', max_length=50, verbose_name='Rəngin adı')),
                ('product_color', models.CharField(help_text='Maximum 50 character', max_length=50, verbose_name='Məhsulun Rəngi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Rəng haqqında')),
            ],
            options={
                'verbose_name': 'Rəng',
                'verbose_name_plural': 'Rənglər',
            },
        ),
        migrations.CreateModel(
            name='ManufacturerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Maximum 50 character', max_length=50, verbose_name='Məhsul İstehsalcısı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='İstehsalçı haqqında')),
            ],
            options={
                'verbose_name': 'İstehsalçı',
                'verbose_name_plural': 'İstehsalçılar',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, verbose_name='Məhsul adı')),
                ('descriptions', models.TextField(blank=True, null=True, verbose_name='Məhsul haqqında')),
                ('special_price', models.FloatField(default=0, verbose_name='Yeni qiymət')),
                ('old_price', models.FloatField(default=0, verbose_name='Köhnə qiymət')),
                ('discount', models.IntegerField(blank=True, null=True, verbose_name='Endirim')),
                ('stock', models.PositiveIntegerField(default=0, help_text='Məhsulun anbarda olan sayı', verbose_name='Stok sayı')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Məhsul haqqında məlumat')),
                ('product_image', models.ImageField(upload_to='product/product_image', verbose_name='Məhsulun Şəkili')),
                ('cov_img', models.ImageField(blank=True, null=True, upload_to='product/cov_img', verbose_name=' Məhsulun üz qabıq şəkili')),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('product_detail_imge1', models.ImageField(blank=True, null=True, upload_to='product/detail_image', verbose_name='Detaylı şəkil-1')),
                ('product_detail_imge2', models.ImageField(blank=True, null=True, upload_to='product/detail_image', verbose_name='Detaylı şəkil-2')),
                ('product_detail_imge3', models.ImageField(blank=True, null=True, upload_to='product/detail_image', verbose_name='Detaylı şəkil-3')),
                ('product_detail_imge4', models.ImageField(blank=True, null=True, upload_to='product/detail_image', verbose_name='Detaylı şəkil-4')),
                ('product_detail_imge5', models.ImageField(blank=True, null=True, upload_to='product/detail_image', verbose_name='Detaylı şəkil-5')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.categorymodel', verbose_name='Məhsulun kateqoriyası')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.colormodel', verbose_name='Məhsul Rəngi')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.manufacturermodel', verbose_name='Məhsulun İstehsalçısı')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Məhsul',
                'verbose_name_plural': 'Bütün Məhsullar',
            },
        ),
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Ad')),
                ('surname', models.CharField(max_length=100, verbose_name='Soyad')),
                ('text', models.TextField(verbose_name='Rəy mətini')),
                ('rating', models.PositiveIntegerField(blank=True, choices=[(1, '1 Star'), (2, '2 Star'), (3, '3 Star'), (4, '4 Star'), (5, '5 Star')], null=True, verbose_name='Qiyymetləndirmə')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Bəyənilmə')),
                ('dislikes', models.PositiveIntegerField(default=0, verbose_name='Bəyənilməmə')),
                ('reply_to_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Cavab verən istifadəçi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='Products.reviewmodel', verbose_name='Ana rəy')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Products.productmodel', verbose_name='Məhsul')),
            ],
            options={
                'verbose_name': 'Komenntariya',
                'verbose_name_plural': 'Rəylər',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['product', '-created'], name='Products_re_product_ed681e_idx'), models.Index(fields=['parent'], name='Products_re_parent__0f95d2_idx'), models.Index(fields=['is_active'], name='Products_re_is_acti_3ebb19_idx')],
            },
        ),
    ]
