# Generated by Django 5.1.3 on 2026-05-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colormodel',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Rəng', 'verbose_name_plural': 'Rənglər'},
        ),
        migrations.AddField(
            model_name='colormodel',
            name='color_code',
            field=models.CharField(default='#000000', help_text='Məsələn: #ff0000 qırmızı üçün', max_length=7, verbose_name='Rəng kodu (CSS)'),
        ),
        migrations.AddField(
            model_name='colormodel',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Sıralama'),
        ),
    ]
