# Generated by Django 5.1.3 on 2026-05-13 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_alter_colormodel_options_colormodel_color_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colormodel',
            options={'verbose_name': 'Rəng', 'verbose_name_plural': 'Rənglər'},
        ),
        migrations.RemoveField(
            model_name='colormodel',
            name='color_code',
        ),
        migrations.RemoveField(
            model_name='colormodel',
            name='order',
        ),
    ]
