# Generated by Django 5.1.3 on 2026-05-14 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_alter_colormodel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colormodel',
            name='title_az',
        ),
        migrations.RemoveField(
            model_name='colormodel',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='colormodel',
            name='title_ru',
        ),
    ]
