# Generated by Django 5.1.3 on 2026-05-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_remove_colormodel_title_az_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colormodel',
            name='title_az',
            field=models.CharField(max_length=50, null=True, verbose_name='Rəngin adı'),
        ),
        migrations.AddField(
            model_name='colormodel',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Rəngin adı'),
        ),
        migrations.AddField(
            model_name='colormodel',
            name='title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Rəngin adı'),
        ),
    ]
