# Generated by Django 5.1.3 on 2026-05-12 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Maksimum 100 simvol', max_length=50, verbose_name='Servis növü')),
                ('title_en', models.CharField(help_text='Maksimum 100 simvol', max_length=50, null=True, verbose_name='Servis növü')),
                ('title_az', models.CharField(help_text='Maksimum 100 simvol', max_length=50, null=True, verbose_name='Servis növü')),
                ('title_ru', models.CharField(help_text='Maksimum 100 simvol', max_length=50, null=True, verbose_name='Servis növü')),
                ('descriptions', models.CharField(max_length=250, verbose_name='Xidmət təsviri')),
                ('descriptions_en', models.CharField(max_length=250, null=True, verbose_name='Xidmət təsviri')),
                ('descriptions_az', models.CharField(max_length=250, null=True, verbose_name='Xidmət təsviri')),
                ('descriptions_ru', models.CharField(max_length=250, null=True, verbose_name='Xidmət təsviri')),
                ('details_header', models.CharField(help_text='Maksimum 250 simvol', max_length=250, verbose_name='Detaylı Xidmətlər başlığı')),
                ('details_header_en', models.CharField(help_text='Maksimum 250 simvol', max_length=250, null=True, verbose_name='Detaylı Xidmətlər başlığı')),
                ('details_header_az', models.CharField(help_text='Maksimum 250 simvol', max_length=250, null=True, verbose_name='Detaylı Xidmətlər başlığı')),
                ('details_header_ru', models.CharField(help_text='Maksimum 250 simvol', max_length=250, null=True, verbose_name='Detaylı Xidmətlər başlığı')),
                ('details_text1', models.TextField(blank=True, null=True, verbose_name='Xidmət haqqında-1')),
                ('details_text1_en', models.TextField(blank=True, null=True, verbose_name='Xidmət haqqında-1')),
                ('details_text1_az', models.TextField(blank=True, null=True, verbose_name='Xidmət haqqında-1')),
                ('details_text1_ru', models.TextField(blank=True, null=True, verbose_name='Xidmət haqqında-1')),
                ('details_text2', models.TextField(blank=True, null=True, verbose_name='Xidmət haqqında-2')),
                ('details_text2_en', models.TextField(blank=True, null=True, verbose_name='Xidmət haqqında-2')),
                ('details_text2_az', models.TextField(blank=True, null=True, verbose_name='Xidmət haqqında-2')),
                ('details_text2_ru', models.TextField(blank=True, null=True, verbose_name='Xidmət haqqında-2')),
                ('details_text3', models.TextField(blank=True, null=True, verbose_name='Xidmət haqqında-3')),
                ('details_text3_en', models.TextField(blank=True, null=True, verbose_name='Xidmət haqqında-3')),
                ('details_text3_az', models.TextField(blank=True, null=True, verbose_name='Xidmət haqqında-3')),
                ('details_text3_ru', models.TextField(blank=True, null=True, verbose_name='Xidmət haqqında-3')),
                ('cov_img', models.ImageField(blank=True, null=True, upload_to='Core/cov_img', verbose_name='Xidmətin üz şəkili')),
                ('icons', models.ImageField(blank=True, null=True, upload_to='Core/service_image', verbose_name='Xidmət şəkili')),
            ],
            options={
                'verbose_name': 'Servis',
                'verbose_name_plural': 'Bütün Servislər',
            },
        ),
    ]
