# Generated by Django 5.1.3 on 2026-05-05 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreTranslation',
            fields=[
                ('servicesmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Core.servicesmodel')),
            ],
            options={
                'abstract': False,
            },
            bases=('Core.servicesmodel',),
        ),
    ]
