# Generated by Django 5.1.3 on 2026-05-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_coretranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesmodel',
            name='descriptions_az',
            field=models.CharField(max_length=250, null=True, verbose_name='Xidmət təsviri'),
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='descriptions_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Xidmət təsviri'),
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='descriptions_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Xidmət təsviri'),
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='details_header_az',
            field=models.CharField(help_text='Maksimum 250 simvol', max_length=250, null=True, verbose_name='Detaylı Xidmətlər başlığı'),
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='details_header_en',
            field=models.CharField(help_text='Maksimum 250 simvol', max_length=250, null=True, verbose_name='Detaylı Xidmətlər başlığı'),
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='details_header_ru',
            field=models.CharField(help_text='Maksimum 250 simvol', max_length=250, null=True, verbose_name='Detaylı Xidmətlər başlığı'),
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='details_text1_az',
            field=models.TextField(blank=True, null=True, verbose_name='Xidmət haqqında-1'),
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='details_text1_en',
            field=models.TextField(blank=True, null=True, verbose_name='Xidmət haqqında-1'),
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='details_text1_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Xidmət haqqında-1'),
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='details_text2_az',
            field=models.TextField(blank=True, null=True, verbose_name='Xidmət haqqında-2'),
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='details_text2_en',
            field=models.TextField(blank=True, null=True, verbose_name='Xidmət haqqında-2'),
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='details_text2_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Xidmət haqqında-2'),
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='details_text3_az',
            field=models.TextField(blank=True, null=True, verbose_name='Xidmət haqqında-3'),
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='details_text3_en',
            field=models.TextField(blank=True, null=True, verbose_name='Xidmət haqqında-3'),
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='details_text3_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Xidmət haqqında-3'),
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='title_az',
            field=models.CharField(help_text='Maksimum 100 simvol', max_length=50, null=True, verbose_name='Servis növü'),
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='title_en',
            field=models.CharField(help_text='Maksimum 100 simvol', max_length=50, null=True, verbose_name='Servis növü'),
        ),
        migrations.AddField(
            model_name='servicesmodel',
            name='title_ru',
            field=models.CharField(help_text='Maksimum 100 simvol', max_length=50, null=True, verbose_name='Servis növü'),
        ),
        migrations.DeleteModel(
            name='CoreTranslation',
        ),
    ]
